// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbqueries

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  emoji
) VALUES (
  $1
)
RETURNING id, created_at, emoji
`

func (q *Queries) CreatePost(ctx context.Context, emoji string) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, emoji)
	var i Post
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Emoji)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, created_at, emoji FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Emoji)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, created_at, emoji FROM posts
ORDER BY id DESC LIMIT 10
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
