// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Emoji     string             `json:"emoji"`
}
